name: csslib_transform
version: 0.0.1
description: A library useful for applications or for sharing on pub.dartlang.org.
dependencies:
  barback: any
  csslib: any
  logging: any
dev_dependencies:
  unittest: any
